// Generated by CoffeeScript 1.9.3
(function() {
  var data, result, schema, v;

  v = require(__dirname + '/../index.js');

  data = {
    foo: 4
  };

  schema = {
    type: "object",
    properties: {
      foo: {
        type: "number",
        acl: {
          create: ["admin", "user"],
          read: ["*"],
          update: ["admin"],
          "delete": ["admin"]
        }
      }
    }
  };

  result = v.validate(data, schema, "create", "user");

  if (result.errors.length !== 1) {
    console.dir(result);
    process.exit(1);
  }

  result = v.validate(data, schema, "create", ["user"]);

  if (result.errors.length !== 0) {
    console.dir(result);
    process.exit(1);
  }

  result = v.validate(data, schema, "read", ["user"]);

  if (result.errors.length !== 0) {
    console.dir(result);
    process.exit(1);
  }

  console.log("tests passed");

  process.exit(0);

}).call(this);
